--------------------------------------------------------
--  파일이 생성됨 - 화요일-1월-07-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table AUDIO_BOOK
--------------------------------------------------------

  CREATE TABLE "BOOKSTORE"."AUDIO_BOOK" 
   (   "ORDERID" VARCHAR2(100 BYTE), 
   "A_NUM" NUMBER, 
   "AUDIO" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table BOOK
--------------------------------------------------------

  CREATE TABLE "BOOKSTORE"."BOOK" 
   (   "H_CODE" VARCHAR2(100 BYTE), 
   "L_CODE" VARCHAR2(100 BYTE), 
   "B_NAME" VARCHAR2(100 BYTE), 
   "B_COMPANY" VARCHAR2(100 BYTE), 
   "B_PRICE" NUMBER, 
   "SALE_PRICE" NUMBER, 
   "BUY_NUM" NUMBER, 
   "STATUS" VARCHAR2(50 BYTE), 
   "ST1" VARCHAR2(50 BYTE), 
   "ST2" VARCHAR2(50 BYTE), 
   "CONTENT" VARCHAR2(4000 BYTE), 
   "CREATED" VARCHAR2(50 BYTE), 
   "B_CODE" VARCHAR2(100 BYTE), 
   "B_IMAGE" VARCHAR2(100 BYTE), 
   "B_TYPE" NUMBER, 
   "WRITER_NAME" VARCHAR2(200 BYTE), 
   "CONTENTS" VARCHAR2(400 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table CART
--------------------------------------------------------

  CREATE TABLE "BOOKSTORE"."CART" 
   (   "P_NUM" NUMBER, 
   "MEMBER_SID" NUMBER, 
   "B_TYPE" NUMBER, 
   "B_CODE" VARCHAR2(100 BYTE), 
   "PRODUCTS_COUNT" VARCHAR2(20 BYTE), 
   "WDATE" VARCHAR2(100 BYTE), 
   "PRICE" NUMBER, 
   "MEMBER_ID" VARCHAR2(50 BYTE), 
   "SALE_PRICE" NUMBER, 
   "B_NAME" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table COMMENTS
--------------------------------------------------------

  CREATE TABLE "BOOKSTORE"."COMMENTS" 
   (   "REVIEW_NUM" NUMBER, 
   "Q_NUM" NUMBER, 
   "REQUEST_NUM" NUMBER, 
   "MEMBER_ID" VARCHAR2(50 BYTE), 
   "CONTENT" VARCHAR2(4000 BYTE), 
   "PASSWORD" VARCHAR2(20 BYTE), 
   "WRITER_NAME" VARCHAR2(50 BYTE), 
   "C_IDX" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table E_BOOK
--------------------------------------------------------

  CREATE TABLE "BOOKSTORE"."E_BOOK" 
   (   "ORDERID" VARCHAR2(100 BYTE), 
   "E_NUM" VARCHAR2(50 BYTE), 
   "E_IMAGE" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table HIGH_CATEGORY
--------------------------------------------------------

  CREATE TABLE "BOOKSTORE"."HIGH_CATEGORY" 
   (   "H_NAME" VARCHAR2(100 BYTE), 
   "H_CODE" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table LOW_CATEGORY
--------------------------------------------------------

  CREATE TABLE "BOOKSTORE"."LOW_CATEGORY" 
   (   "L_NAME" VARCHAR2(100 BYTE), 
   "L_CODE" VARCHAR2(100 BYTE), 
   "H_CODE" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table MEMBER
--------------------------------------------------------

  CREATE TABLE "BOOKSTORE"."MEMBER" 
   (   "MEMBER_ID" VARCHAR2(50 BYTE), 
   "USERNAME" VARCHAR2(20 BYTE), 
   "PASSWORD" VARCHAR2(20 BYTE), 
   "EMAIL" VARCHAR2(50 BYTE), 
   "ZIPCODE" VARCHAR2(100 BYTE), 
   "ADDRESS1" VARCHAR2(100 BYTE), 
   "ADDRESS2" VARCHAR2(100 BYTE), 
   "MOBILEPHONE" VARCHAR2(20 BYTE), 
   "REGDATE" VARCHAR2(50 BYTE), 
   "U_STATUS" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table NOTICE
--------------------------------------------------------

  CREATE TABLE "BOOKSTORE"."NOTICE" 
   (   "N_NUM" NUMBER, 
   "SUBJECT" VARCHAR2(50 BYTE), 
   "CONTENT" VARCHAR2(4000 BYTE), 
   "WDATE" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ORDERS
--------------------------------------------------------

  CREATE TABLE "BOOKSTORE"."ORDERS" 
   (   "O_NUM" NUMBER, 
   "ORDERID" VARCHAR2(100 BYTE), 
   "MEMBER_ID" VARCHAR2(20 BYTE), 
   "B_TYPE" NUMBER, 
   "B_CODE" VARCHAR2(100 BYTE), 
   "PRODUCTS_COUNT" NUMBER, 
   "BUYER_NAME" VARCHAR2(50 BYTE), 
   "BUYER_ZIPCODE" VARCHAR2(100 BYTE), 
   "BUYER_ADDRESS" VARCHAR2(100 BYTE), 
   "BUYER_PHONE" VARCHAR2(50 BYTE), 
   "BUYER_EMAIL" VARCHAR2(50 BYTE), 
   "RECIPIENT_NAME" VARCHAR2(50 BYTE), 
   "RECIPIENT_ZIPCODE" VARCHAR2(100 BYTE), 
   "RECIPIENT_ADDRESS" VARCHAR2(100 BYTE), 
   "RECIPIENT_PHONE" VARCHAR2(50 BYTE), 
   "MESSAGE" VARCHAR2(50 BYTE), 
   "AMOUNT" NUMBER, 
   "PAY_TYPE" VARCHAR2(50 BYTE), 
   "BANK_NAME" VARCHAR2(50 BYTE), 
   "DEPOSIT_NAME" VARCHAR2(50 BYTE), 
   "DEPOSIT_DATE" VARCHAR2(50 BYTE), 
   "STATE" VARCHAR2(50 BYTE), 
   "CANCEL" NUMBER, 
   "WDATE" VARCHAR2(50 BYTE), 
   "B_NAME" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table QNA
--------------------------------------------------------

  CREATE TABLE "BOOKSTORE"."QNA" 
   (   "Q_NUM" NUMBER, 
   "MEMBER_ID" VARCHAR2(50 BYTE), 
   "USERNAME" VARCHAR2(20 BYTE), 
   "PASSWORD" VARCHAR2(20 BYTE), 
   "SUBJECT" VARCHAR2(20 BYTE), 
   "CATEGORY" VARCHAR2(20 BYTE), 
   "R_CNTENT" CLOB, 
   "UPLOAD" VARCHAR2(100 BYTE), 
   "B_CODE" VARCHAR2(100 BYTE), 
   "B_TYPE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("R_CNTENT") STORE AS BASICFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table REQUEST
--------------------------------------------------------

  CREATE TABLE "BOOKSTORE"."REQUEST" 
   (   "REQUEST_NUM" NUMBER, 
   "MEMBER_ID" VARCHAR2(20 BYTE), 
   "SUBJECT" VARCHAR2(50 BYTE), 
   "R_CNTENT" CLOB, 
   "PASSWORD" VARCHAR2(20 BYTE), 
   "UPLOAD" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("R_CNTENT") STORE AS BASICFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table REVIEW
--------------------------------------------------------

  CREATE TABLE "BOOKSTORE"."REVIEW" 
   (   "REVIEW_NUM" NUMBER, 
   "MEMBER_ID" VARCHAR2(50 BYTE), 
   "USERNAME" VARCHAR2(20 BYTE), 
   "PASSWORD" VARCHAR2(20 BYTE), 
   "SUBJECT" VARCHAR2(50 BYTE), 
   "R_CNTENT" CLOB, 
   "UPLOAD" VARCHAR2(100 BYTE), 
   "B_CODE" VARCHAR2(100 BYTE), 
   "ORDERID" VARCHAR2(100 BYTE), 
   "B_TYPE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("R_CNTENT") STORE AS BASICFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
REM INSERTING into BOOKSTORE.AUDIO_BOOK
SET DEFINE OFF;
REM INSERTING into BOOKSTORE.BOOK
SET DEFINE OFF;
REM INSERTING into BOOKSTORE.CART
SET DEFINE OFF;
REM INSERTING into BOOKSTORE.COMMENTS
SET DEFINE OFF;
REM INSERTING into BOOKSTORE.E_BOOK
SET DEFINE OFF;
REM INSERTING into BOOKSTORE.HIGH_CATEGORY
SET DEFINE OFF;
REM INSERTING into BOOKSTORE.LOW_CATEGORY
SET DEFINE OFF;
REM INSERTING into BOOKSTORE.MEMBER
SET DEFINE OFF;
REM INSERTING into BOOKSTORE.NOTICE
SET DEFINE OFF;
REM INSERTING into BOOKSTORE.ORDERS
SET DEFINE OFF;
REM INSERTING into BOOKSTORE.QNA
SET DEFINE OFF;
REM INSERTING into BOOKSTORE.REQUEST
SET DEFINE OFF;
REM INSERTING into BOOKSTORE.REVIEW
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index AUDIO_BOOK_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BOOKSTORE"."AUDIO_BOOK_PK" ON "BOOKSTORE"."AUDIO_BOOK" ("A_NUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index HIGH_CATEGORY_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BOOKSTORE"."HIGH_CATEGORY_PK" ON "BOOKSTORE"."HIGH_CATEGORY" ("H_CODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ORDERS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BOOKSTORE"."ORDERS_PK" ON "BOOKSTORE"."ORDERS" ("O_NUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index COMMENTS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BOOKSTORE"."COMMENTS_PK" ON "BOOKSTORE"."COMMENTS" ("C_IDX") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ORDERS_UK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "BOOKSTORE"."ORDERS_UK1" ON "BOOKSTORE"."ORDERS" ("ORDERID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index REVIEW_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BOOKSTORE"."REVIEW_PK" ON "BOOKSTORE"."REVIEW" ("REVIEW_NUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index QNA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BOOKSTORE"."QNA_PK" ON "BOOKSTORE"."QNA" ("Q_NUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index REQUEST_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BOOKSTORE"."REQUEST_PK" ON "BOOKSTORE"."REQUEST" ("REQUEST_NUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index BOOK_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BOOKSTORE"."BOOK_PK" ON "BOOKSTORE"."BOOK" ("B_CODE", "B_TYPE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index LOW_CATEGORY_PK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "BOOKSTORE"."LOW_CATEGORY_PK1" ON "BOOKSTORE"."LOW_CATEGORY" ("L_CODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index MEMBER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BOOKSTORE"."MEMBER_PK" ON "BOOKSTORE"."MEMBER" ("MEMBER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index NOTICE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BOOKSTORE"."NOTICE_PK" ON "BOOKSTORE"."NOTICE" ("N_NUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index E_BOOK_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BOOKSTORE"."E_BOOK_PK" ON "BOOKSTORE"."E_BOOK" ("E_NUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index CART_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BOOKSTORE"."CART_PK" ON "BOOKSTORE"."CART" ("P_NUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table MEMBER
--------------------------------------------------------

  ALTER TABLE "BOOKSTORE"."MEMBER" ADD CONSTRAINT "MEMBER_PK" PRIMARY KEY ("MEMBER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "BOOKSTORE"."MEMBER" MODIFY ("U_STATUS" NOT NULL ENABLE);
  ALTER TABLE "BOOKSTORE"."MEMBER" MODIFY ("REGDATE" NOT NULL ENABLE);
  ALTER TABLE "BOOKSTORE"."MEMBER" MODIFY ("MOBILEPHONE" NOT NULL ENABLE);
  ALTER TABLE "BOOKSTORE"."MEMBER" MODIFY ("ADDRESS2" NOT NULL ENABLE);
  ALTER TABLE "BOOKSTORE"."MEMBER" MODIFY ("ADDRESS1" NOT NULL ENABLE);
  ALTER TABLE "BOOKSTORE"."MEMBER" MODIFY ("ZIPCODE" NOT NULL ENABLE);
  ALTER TABLE "BOOKSTORE"."MEMBER" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "BOOKSTORE"."MEMBER" MODIFY ("PASSWORD" NOT NULL ENABLE);
  ALTER TABLE "BOOKSTORE"."MEMBER" MODIFY ("USERNAME" NOT NULL ENABLE);
  ALTER TABLE "BOOKSTORE"."MEMBER" MODIFY ("MEMBER_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ORDERS
--------------------------------------------------------

  ALTER TABLE "BOOKSTORE"."ORDERS" ADD CONSTRAINT "ORDERS_UK1" UNIQUE ("ORDERID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "BOOKSTORE"."ORDERS" ADD CONSTRAINT "ORDERS_PK" PRIMARY KEY ("O_NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "BOOKSTORE"."ORDERS" MODIFY ("B_NAME" NOT NULL ENABLE);
  ALTER TABLE "BOOKSTORE"."ORDERS" MODIFY ("WDATE" NOT NULL ENABLE);
  ALTER TABLE "BOOKSTORE"."ORDERS" MODIFY ("CANCEL" NOT NULL ENABLE);
  ALTER TABLE "BOOKSTORE"."ORDERS" MODIFY ("STATE" NOT NULL ENABLE);
  ALTER TABLE "BOOKSTORE"."ORDERS" MODIFY ("PAY_TYPE" NOT NULL ENABLE);
  ALTER TABLE "BOOKSTORE"."ORDERS" MODIFY ("AMOUNT" NOT NULL ENABLE);
  ALTER TABLE "BOOKSTORE"."ORDERS" MODIFY ("RECIPIENT_PHONE" NOT NULL ENABLE);
  ALTER TABLE "BOOKSTORE"."ORDERS" MODIFY ("RECIPIENT_ADDRESS" NOT NULL ENABLE);
  ALTER TABLE "BOOKSTORE"."ORDERS" MODIFY ("RECIPIENT_ZIPCODE" NOT NULL ENABLE);
  ALTER TABLE "BOOKSTORE"."ORDERS" MODIFY ("RECIPIENT_NAME" NOT NULL ENABLE);
  ALTER TABLE "BOOKSTORE"."ORDERS" MODIFY ("BUYER_PHONE" NOT NULL ENABLE);
  ALTER TABLE "BOOKSTORE"."ORDERS" MODIFY ("BUYER_ADDRESS" NOT NULL ENABLE);
  ALTER TABLE "BOOKSTORE"."ORDERS" MODIFY ("BUYER_ZIPCODE" NOT NULL ENABLE);
  ALTER TABLE "BOOKSTORE"."ORDERS" MODIFY ("BUYER_NAME" NOT NULL ENABLE);
  ALTER TABLE "BOOKSTORE"."ORDERS" MODIFY ("PRODUCTS_COUNT" NOT NULL ENABLE);
  ALTER TABLE "BOOKSTORE"."ORDERS" MODIFY ("B_CODE" NOT NULL ENABLE);
  ALTER TABLE "BOOKSTORE"."ORDERS" MODIFY ("B_TYPE" NOT NULL ENABLE);
  ALTER TABLE "BOOKSTORE"."ORDERS" MODIFY ("MEMBER_ID" NOT NULL ENABLE);
  ALTER TABLE "BOOKSTORE"."ORDERS" MODIFY ("ORDERID" NOT NULL ENABLE);
  ALTER TABLE "BOOKSTORE"."ORDERS" MODIFY ("O_NUM" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table E_BOOK
--------------------------------------------------------

  ALTER TABLE "BOOKSTORE"."E_BOOK" ADD CONSTRAINT "E_BOOK_PK" PRIMARY KEY ("E_NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "BOOKSTORE"."E_BOOK" MODIFY ("E_IMAGE" NOT NULL ENABLE);
  ALTER TABLE "BOOKSTORE"."E_BOOK" MODIFY ("E_NUM" NOT NULL ENABLE);
  ALTER TABLE "BOOKSTORE"."E_BOOK" MODIFY ("ORDERID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table COMMENTS
--------------------------------------------------------

  ALTER TABLE "BOOKSTORE"."COMMENTS" ADD CONSTRAINT "COMMENTS_PK" PRIMARY KEY ("C_IDX")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "BOOKSTORE"."COMMENTS" MODIFY ("C_IDX" NOT NULL ENABLE);
  ALTER TABLE "BOOKSTORE"."COMMENTS" MODIFY ("WRITER_NAME" NOT NULL ENABLE);
  ALTER TABLE "BOOKSTORE"."COMMENTS" MODIFY ("PASSWORD" NOT NULL ENABLE);
  ALTER TABLE "BOOKSTORE"."COMMENTS" MODIFY ("CONTENT" NOT NULL ENABLE);
  ALTER TABLE "BOOKSTORE"."COMMENTS" MODIFY ("MEMBER_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CART
--------------------------------------------------------

  ALTER TABLE "BOOKSTORE"."CART" ADD CONSTRAINT "CART_PK" PRIMARY KEY ("P_NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "BOOKSTORE"."CART" MODIFY ("B_NAME" NOT NULL ENABLE);
  ALTER TABLE "BOOKSTORE"."CART" MODIFY ("MEMBER_ID" NOT NULL ENABLE);
  ALTER TABLE "BOOKSTORE"."CART" MODIFY ("PRICE" NOT NULL ENABLE);
  ALTER TABLE "BOOKSTORE"."CART" MODIFY ("WDATE" NOT NULL ENABLE);
  ALTER TABLE "BOOKSTORE"."CART" MODIFY ("PRODUCTS_COUNT" NOT NULL ENABLE);
  ALTER TABLE "BOOKSTORE"."CART" MODIFY ("B_CODE" NOT NULL ENABLE);
  ALTER TABLE "BOOKSTORE"."CART" MODIFY ("B_TYPE" NOT NULL ENABLE);
  ALTER TABLE "BOOKSTORE"."CART" MODIFY ("MEMBER_SID" NOT NULL ENABLE);
  ALTER TABLE "BOOKSTORE"."CART" MODIFY ("P_NUM" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table REVIEW
--------------------------------------------------------

  ALTER TABLE "BOOKSTORE"."REVIEW" ADD CONSTRAINT "REVIEW_PK" PRIMARY KEY ("REVIEW_NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "BOOKSTORE"."REVIEW" MODIFY ("B_TYPE" NOT NULL ENABLE);
  ALTER TABLE "BOOKSTORE"."REVIEW" MODIFY ("ORDERID" NOT NULL ENABLE);
  ALTER TABLE "BOOKSTORE"."REVIEW" MODIFY ("B_CODE" NOT NULL ENABLE);
  ALTER TABLE "BOOKSTORE"."REVIEW" MODIFY ("R_CNTENT" NOT NULL ENABLE);
  ALTER TABLE "BOOKSTORE"."REVIEW" MODIFY ("SUBJECT" NOT NULL ENABLE);
  ALTER TABLE "BOOKSTORE"."REVIEW" MODIFY ("PASSWORD" NOT NULL ENABLE);
  ALTER TABLE "BOOKSTORE"."REVIEW" MODIFY ("USERNAME" NOT NULL ENABLE);
  ALTER TABLE "BOOKSTORE"."REVIEW" MODIFY ("MEMBER_ID" NOT NULL ENABLE);
  ALTER TABLE "BOOKSTORE"."REVIEW" MODIFY ("REVIEW_NUM" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table AUDIO_BOOK
--------------------------------------------------------

  ALTER TABLE "BOOKSTORE"."AUDIO_BOOK" ADD CONSTRAINT "AUDIO_BOOK_PK" PRIMARY KEY ("A_NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "BOOKSTORE"."AUDIO_BOOK" MODIFY ("AUDIO" NOT NULL ENABLE);
  ALTER TABLE "BOOKSTORE"."AUDIO_BOOK" MODIFY ("A_NUM" NOT NULL ENABLE);
  ALTER TABLE "BOOKSTORE"."AUDIO_BOOK" MODIFY ("ORDERID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table REQUEST
--------------------------------------------------------

  ALTER TABLE "BOOKSTORE"."REQUEST" ADD CONSTRAINT "REQUEST_PK" PRIMARY KEY ("REQUEST_NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "BOOKSTORE"."REQUEST" MODIFY ("PASSWORD" NOT NULL ENABLE);
  ALTER TABLE "BOOKSTORE"."REQUEST" MODIFY ("R_CNTENT" NOT NULL ENABLE);
  ALTER TABLE "BOOKSTORE"."REQUEST" MODIFY ("SUBJECT" NOT NULL ENABLE);
  ALTER TABLE "BOOKSTORE"."REQUEST" MODIFY ("MEMBER_ID" NOT NULL ENABLE);
  ALTER TABLE "BOOKSTORE"."REQUEST" MODIFY ("REQUEST_NUM" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table LOW_CATEGORY
--------------------------------------------------------

  ALTER TABLE "BOOKSTORE"."LOW_CATEGORY" ADD CONSTRAINT "LOW_CATEGORY_PK" PRIMARY KEY ("L_CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "BOOKSTORE"."LOW_CATEGORY" MODIFY ("H_CODE" NOT NULL ENABLE);
  ALTER TABLE "BOOKSTORE"."LOW_CATEGORY" MODIFY ("L_CODE" NOT NULL ENABLE);
  ALTER TABLE "BOOKSTORE"."LOW_CATEGORY" MODIFY ("L_NAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table NOTICE
--------------------------------------------------------

  ALTER TABLE "BOOKSTORE"."NOTICE" ADD CONSTRAINT "NOTICE_PK" PRIMARY KEY ("N_NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "BOOKSTORE"."NOTICE" MODIFY ("WDATE" NOT NULL ENABLE);
  ALTER TABLE "BOOKSTORE"."NOTICE" MODIFY ("CONTENT" NOT NULL ENABLE);
  ALTER TABLE "BOOKSTORE"."NOTICE" MODIFY ("SUBJECT" NOT NULL ENABLE);
  ALTER TABLE "BOOKSTORE"."NOTICE" MODIFY ("N_NUM" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table HIGH_CATEGORY
--------------------------------------------------------

  ALTER TABLE "BOOKSTORE"."HIGH_CATEGORY" ADD CONSTRAINT "HIGH_CATEGORY_PK" PRIMARY KEY ("H_CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "BOOKSTORE"."HIGH_CATEGORY" MODIFY ("H_CODE" NOT NULL ENABLE);
  ALTER TABLE "BOOKSTORE"."HIGH_CATEGORY" MODIFY ("H_NAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table BOOK
--------------------------------------------------------

  ALTER TABLE "BOOKSTORE"."BOOK" ADD CONSTRAINT "BOOK_PK" PRIMARY KEY ("B_CODE", "B_TYPE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "BOOKSTORE"."BOOK" MODIFY ("CONTENTS" NOT NULL ENABLE);
  ALTER TABLE "BOOKSTORE"."BOOK" MODIFY ("WRITER_NAME" NOT NULL ENABLE);
  ALTER TABLE "BOOKSTORE"."BOOK" MODIFY ("B_TYPE" NOT NULL ENABLE);
  ALTER TABLE "BOOKSTORE"."BOOK" MODIFY ("B_IMAGE" NOT NULL ENABLE);
  ALTER TABLE "BOOKSTORE"."BOOK" MODIFY ("B_CODE" NOT NULL ENABLE);
  ALTER TABLE "BOOKSTORE"."BOOK" MODIFY ("CREATED" NOT NULL ENABLE);
  ALTER TABLE "BOOKSTORE"."BOOK" MODIFY ("CONTENT" NOT NULL ENABLE);
  ALTER TABLE "BOOKSTORE"."BOOK" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "BOOKSTORE"."BOOK" MODIFY ("BUY_NUM" NOT NULL ENABLE);
  ALTER TABLE "BOOKSTORE"."BOOK" MODIFY ("SALE_PRICE" NOT NULL ENABLE);
  ALTER TABLE "BOOKSTORE"."BOOK" MODIFY ("B_PRICE" NOT NULL ENABLE);
  ALTER TABLE "BOOKSTORE"."BOOK" MODIFY ("B_COMPANY" NOT NULL ENABLE);
  ALTER TABLE "BOOKSTORE"."BOOK" MODIFY ("B_NAME" NOT NULL ENABLE);
  ALTER TABLE "BOOKSTORE"."BOOK" MODIFY ("L_CODE" NOT NULL ENABLE);
  ALTER TABLE "BOOKSTORE"."BOOK" MODIFY ("H_CODE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table QNA
--------------------------------------------------------

  ALTER TABLE "BOOKSTORE"."QNA" ADD CONSTRAINT "QNA_PK" PRIMARY KEY ("Q_NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "BOOKSTORE"."QNA" MODIFY ("B_TYPE" NOT NULL ENABLE);
  ALTER TABLE "BOOKSTORE"."QNA" MODIFY ("B_CODE" NOT NULL ENABLE);
  ALTER TABLE "BOOKSTORE"."QNA" MODIFY ("R_CNTENT" NOT NULL ENABLE);
  ALTER TABLE "BOOKSTORE"."QNA" MODIFY ("CATEGORY" NOT NULL ENABLE);
  ALTER TABLE "BOOKSTORE"."QNA" MODIFY ("SUBJECT" NOT NULL ENABLE);
  ALTER TABLE "BOOKSTORE"."QNA" MODIFY ("PASSWORD" NOT NULL ENABLE);
  ALTER TABLE "BOOKSTORE"."QNA" MODIFY ("USERNAME" NOT NULL ENABLE);
  ALTER TABLE "BOOKSTORE"."QNA" MODIFY ("MEMBER_ID" NOT NULL ENABLE);
  ALTER TABLE "BOOKSTORE"."QNA" MODIFY ("Q_NUM" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table AUDIO_BOOK
--------------------------------------------------------

  ALTER TABLE "BOOKSTORE"."AUDIO_BOOK" ADD CONSTRAINT "AUDIO_BOOK_FK1" FOREIGN KEY ("ORDERID")
     REFERENCES "BOOKSTORE"."ORDERS" ("ORDERID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table BOOK
--------------------------------------------------------

  ALTER TABLE "BOOKSTORE"."BOOK" ADD CONSTRAINT "BOOK_FK1" FOREIGN KEY ("L_CODE")
     REFERENCES "BOOKSTORE"."LOW_CATEGORY" ("L_CODE") ENABLE;
  ALTER TABLE "BOOKSTORE"."BOOK" ADD CONSTRAINT "BOOK_FK2" FOREIGN KEY ("H_CODE")
     REFERENCES "BOOKSTORE"."HIGH_CATEGORY" ("H_CODE") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CART
--------------------------------------------------------

  ALTER TABLE "BOOKSTORE"."CART" ADD CONSTRAINT "CART_FK1" FOREIGN KEY ("MEMBER_ID")
     REFERENCES "BOOKSTORE"."MEMBER" ("MEMBER_ID") ENABLE;
  ALTER TABLE "BOOKSTORE"."CART" ADD CONSTRAINT "CART_FK2" FOREIGN KEY ("B_CODE", "B_TYPE")
     REFERENCES "BOOKSTORE"."BOOK" ("B_CODE", "B_TYPE") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table COMMENTS
--------------------------------------------------------

  ALTER TABLE "BOOKSTORE"."COMMENTS" ADD CONSTRAINT "COMMENTS_FK1" FOREIGN KEY ("MEMBER_ID")
     REFERENCES "BOOKSTORE"."MEMBER" ("MEMBER_ID") ENABLE;
  ALTER TABLE "BOOKSTORE"."COMMENTS" ADD CONSTRAINT "COMMENTS_FK3" FOREIGN KEY ("Q_NUM")
     REFERENCES "BOOKSTORE"."QNA" ("Q_NUM") ENABLE;
  ALTER TABLE "BOOKSTORE"."COMMENTS" ADD CONSTRAINT "COMMENTS_FK4" FOREIGN KEY ("REVIEW_NUM")
     REFERENCES "BOOKSTORE"."REVIEW" ("REVIEW_NUM") ENABLE;
  ALTER TABLE "BOOKSTORE"."COMMENTS" ADD CONSTRAINT "COMMENTS_FK5" FOREIGN KEY ("REQUEST_NUM")
     REFERENCES "BOOKSTORE"."REQUEST" ("REQUEST_NUM") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table E_BOOK
--------------------------------------------------------

  ALTER TABLE "BOOKSTORE"."E_BOOK" ADD CONSTRAINT "E_BOOK_FK1" FOREIGN KEY ("ORDERID")
     REFERENCES "BOOKSTORE"."ORDERS" ("ORDERID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ORDERS
--------------------------------------------------------

  ALTER TABLE "BOOKSTORE"."ORDERS" ADD CONSTRAINT "ORDERS_FK1" FOREIGN KEY ("MEMBER_ID")
     REFERENCES "BOOKSTORE"."MEMBER" ("MEMBER_ID") ENABLE;
  ALTER TABLE "BOOKSTORE"."ORDERS" ADD CONSTRAINT "ORDERS_FK2" FOREIGN KEY ("B_CODE", "B_TYPE")
     REFERENCES "BOOKSTORE"."BOOK" ("B_CODE", "B_TYPE") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table QNA
--------------------------------------------------------

  ALTER TABLE "BOOKSTORE"."QNA" ADD CONSTRAINT "QNA_FK1" FOREIGN KEY ("B_CODE", "B_TYPE")
     REFERENCES "BOOKSTORE"."BOOK" ("B_CODE", "B_TYPE") ENABLE;
  ALTER TABLE "BOOKSTORE"."QNA" ADD CONSTRAINT "QNA_FK3" FOREIGN KEY ("MEMBER_ID")
     REFERENCES "BOOKSTORE"."MEMBER" ("MEMBER_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table REQUEST
--------------------------------------------------------

  ALTER TABLE "BOOKSTORE"."REQUEST" ADD CONSTRAINT "REQUEST_FK1" FOREIGN KEY ("MEMBER_ID")
     REFERENCES "BOOKSTORE"."MEMBER" ("MEMBER_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table REVIEW
--------------------------------------------------------

  ALTER TABLE "BOOKSTORE"."REVIEW" ADD CONSTRAINT "REVIEW_FK1" FOREIGN KEY ("MEMBER_ID")
     REFERENCES "BOOKSTORE"."MEMBER" ("MEMBER_ID") ENABLE;
  ALTER TABLE "BOOKSTORE"."REVIEW" ADD CONSTRAINT "REVIEW_FK2" FOREIGN KEY ("ORDERID")
     REFERENCES "BOOKSTORE"."ORDERS" ("ORDERID") ENABLE;
  ALTER TABLE "BOOKSTORE"."REVIEW" ADD CONSTRAINT "REVIEW_FK3" FOREIGN KEY ("B_CODE", "B_TYPE")
     REFERENCES "BOOKSTORE"."BOOK" ("B_CODE", "B_TYPE") ENABLE;
     
  COMMIT;   